//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.Personator {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="basicHttpBindingConfigEndpoint", Namespace="urn:MelissaDataPersonator")]
    public partial class ServicemdContactVerifySOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback doContactVerifyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicemdContactVerifySOAP() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_net_melissadata_personator_ServicemdContactVerifySOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event doContactVerifyCompletedEventHandler doContactVerifyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:MelissaDataPersonator/ServicemdContactVerifySOAP/doContactVerify", RequestNamespace="urn:MelissaDataPersonator", ResponseNamespace="urn:MelissaDataPersonator", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response doContactVerify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Request Request) {
            object[] results = this.Invoke("doContactVerify", new object[] {
                        Request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void doContactVerifyAsync(Request Request) {
            this.doContactVerifyAsync(Request, null);
        }
        
        /// <remarks/>
        public void doContactVerifyAsync(Request Request, object userState) {
            if ((this.doContactVerifyOperationCompleted == null)) {
                this.doContactVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoContactVerifyOperationCompleted);
            }
            this.InvokeAsync("doContactVerify", new object[] {
                        Request}, this.doContactVerifyOperationCompleted, userState);
        }
        
        private void OndoContactVerifyOperationCompleted(object arg) {
            if ((this.doContactVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doContactVerifyCompleted(this, new doContactVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    public partial class Request {
        
        private string actionsField;
        
        private string columnsField;
        
        private string customerIDField;
        
        private string optionsField;
        
        private RequestRecord[] recordsField;
        
        private string transmissionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public RequestRecord[] Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransmissionReference {
            get {
                return this.transmissionReferenceField;
            }
            set {
                this.transmissionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    public partial class RequestRecord {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string birthDayField;
        
        private string birthMonthField;
        
        private string birthYearField;
        
        private string cityField;
        
        private string companyNameField;
        
        private string countryField;
        
        private string emailAddressField;
        
        private string firstNameField;
        
        private string freeFormField;
        
        private string fullNameField;
        
        private string iPAddressField;
        
        private string lastLineField;
        
        private string lastNameField;
        
        private string melissaAddressKeyField;
        
        private string phoneNumberField;
        
        private string postalCodeField;
        
        private string recordIDField;
        
        private string reservedField;
        
        private string socialSecurityField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthMonth {
            get {
                return this.birthMonthField;
            }
            set {
                this.birthMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthYear {
            get {
                return this.birthYearField;
            }
            set {
                this.birthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FreeForm {
            get {
                return this.freeFormField;
            }
            set {
                this.freeFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastLine {
            get {
                return this.lastLineField;
            }
            set {
                this.lastLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MelissaAddressKey {
            get {
                return this.melissaAddressKeyField;
            }
            set {
                this.melissaAddressKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SocialSecurity {
            get {
                return this.socialSecurityField;
            }
            set {
                this.socialSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    public partial class ResponseRecord {
        
        private string addressDeliveryInstallationField;
        
        private string addressExtrasField;
        
        private string addressHouseNumberField;
        
        private string addressKeyField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLockBoxField;
        
        private string addressPostDirectionField;
        
        private string addressPreDirectionField;
        
        private string addressPrivateMailboxNameField;
        
        private string addressPrivateMailboxRangeField;
        
        private string addressRouteServiceField;
        
        private string addressStreetNameField;
        
        private string addressStreetSuffixField;
        
        private string addressSuiteNameField;
        
        private string addressSuiteNumberField;
        
        private string addressTypeCodeField;
        
        private string areaCodeField;
        
        private string cBSACodeField;
        
        private string cBSADivisionCodeField;
        
        private string cBSADivisionLevelField;
        
        private string cBSADivisionTitleField;
        
        private string cBSALevelField;
        
        private string cBSATitleField;
        
        private string carrierRouteField;
        
        private string censusBlockField;
        
        private string censusKeyField;
        
        private string censusTractField;
        
        private string childrenAgeRangeField;
        
        private string cityField;
        
        private string cityAbbreviationField;
        
        private string companyNameField;
        
        private string congressionalDistrictField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string countyFIPSField;
        
        private string countyNameField;
        
        private string countySubdivisionCodeField;
        
        private string countySubdivisionNameField;
        
        private string creditCardUserField;
        
        private string dateOfBirthField;
        
        private string dateOfDeathField;
        
        private string deliveryIndicatorField;
        
        private string deliveryPointCheckDigitField;
        
        private string deliveryPointCodeField;
        
        private string demographicsGenderField;
        
        private string demographicsResultsField;
        
        private string distanceAddressToIPField;
        
        private string domainNameField;
        
        private string educationField;
        
        private string elementarySchoolDistrictCodeField;
        
        private string elementarySchoolDistrictNameField;
        
        private string emailAddressField;
        
        private string estimatedHomeValueField;
        
        private string ethnicCodeField;
        
        private string ethnicGroupField;
        
        private string genderField;
        
        private string gender2Field;
        
        private string householdIncomeField;
        
        private string householdSizeField;
        
        private string iPAddressField;
        
        private string iPCityField;
        
        private string iPConnectionSpeedField;
        
        private string iPConnectionTypeField;
        
        private string iPContinentField;
        
        private string iPCountryAbbreviationField;
        
        private string iPCountryNameField;
        
        private string iPDomainNameField;
        
        private string iPISPNameField;
        
        private string iPLatitudeField;
        
        private string iPLongitudeField;
        
        private string iPPostalCodeField;
        
        private string iPProxyDescriptionField;
        
        private string iPProxyTypeField;
        
        private string iPRegionField;
        
        private string iPUTCField;
        
        private string latitudeField;
        
        private string lengthOfResidenceField;
        
        private string longitudeField;
        
        private string mailboxNameField;
        
        private string maritalStatusField;
        
        private string melissaAddressKeyField;
        
        private string melissaAddressKeyBaseField;
        
        private string moveDateField;
        
        private string nameFirstField;
        
        private string nameFirst2Field;
        
        private string nameFullField;
        
        private string nameLastField;
        
        private string nameLast2Field;
        
        private string nameMiddleField;
        
        private string nameMiddle2Field;
        
        private string namePrefixField;
        
        private string namePrefix2Field;
        
        private string nameSuffixField;
        
        private string nameSuffix2Field;
        
        private string newAreaCodeField;
        
        private string occupationField;
        
        private string ownRentField;
        
        private string phoneCountryCodeField;
        
        private string phoneCountryNameField;
        
        private string phoneExtensionField;
        
        private string phoneNumberField;
        
        private string phonePrefixField;
        
        private string phoneSuffixField;
        
        private string placeCodeField;
        
        private string placeNameField;
        
        private string plus4Field;
        
        private string politicalPartyField;
        
        private string postalCodeField;
        
        private string presenceOfChildrenField;
        
        private string presenceOfSeniorField;
        
        private string privateMailBoxField;
        
        private string recordExtrasField;
        
        private string recordIDField;
        
        private string reservedField;
        
        private string resultsField;
        
        private string salutationField;
        
        private string secondarySchoolDistrictCodeField;
        
        private string secondarySchoolDistrictNameField;
        
        private string stateField;
        
        private string stateDistrictLowerField;
        
        private string stateDistrictUpperField;
        
        private string stateNameField;
        
        private string suiteField;
        
        private string topLevelDomainField;
        
        private string typesOfVehiclesField;
        
        private string uTCField;
        
        private string unifiedSchoolDistrictCodeField;
        
        private string unifiedSchoolDistrictNameField;
        
        private string urbanizationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressDeliveryInstallation {
            get {
                return this.addressDeliveryInstallationField;
            }
            set {
                this.addressDeliveryInstallationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressExtras {
            get {
                return this.addressExtrasField;
            }
            set {
                this.addressExtrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressHouseNumber {
            get {
                return this.addressHouseNumberField;
            }
            set {
                this.addressHouseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressKey {
            get {
                return this.addressKeyField;
            }
            set {
                this.addressKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLockBox {
            get {
                return this.addressLockBoxField;
            }
            set {
                this.addressLockBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressPostDirection {
            get {
                return this.addressPostDirectionField;
            }
            set {
                this.addressPostDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressPreDirection {
            get {
                return this.addressPreDirectionField;
            }
            set {
                this.addressPreDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressPrivateMailboxName {
            get {
                return this.addressPrivateMailboxNameField;
            }
            set {
                this.addressPrivateMailboxNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressPrivateMailboxRange {
            get {
                return this.addressPrivateMailboxRangeField;
            }
            set {
                this.addressPrivateMailboxRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressRouteService {
            get {
                return this.addressRouteServiceField;
            }
            set {
                this.addressRouteServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressStreetName {
            get {
                return this.addressStreetNameField;
            }
            set {
                this.addressStreetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressStreetSuffix {
            get {
                return this.addressStreetSuffixField;
            }
            set {
                this.addressStreetSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressSuiteName {
            get {
                return this.addressSuiteNameField;
            }
            set {
                this.addressSuiteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressSuiteNumber {
            get {
                return this.addressSuiteNumberField;
            }
            set {
                this.addressSuiteNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressTypeCode {
            get {
                return this.addressTypeCodeField;
            }
            set {
                this.addressTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSACode {
            get {
                return this.cBSACodeField;
            }
            set {
                this.cBSACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSADivisionCode {
            get {
                return this.cBSADivisionCodeField;
            }
            set {
                this.cBSADivisionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSADivisionLevel {
            get {
                return this.cBSADivisionLevelField;
            }
            set {
                this.cBSADivisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSADivisionTitle {
            get {
                return this.cBSADivisionTitleField;
            }
            set {
                this.cBSADivisionTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSALevel {
            get {
                return this.cBSALevelField;
            }
            set {
                this.cBSALevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBSATitle {
            get {
                return this.cBSATitleField;
            }
            set {
                this.cBSATitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CensusBlock {
            get {
                return this.censusBlockField;
            }
            set {
                this.censusBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CensusKey {
            get {
                return this.censusKeyField;
            }
            set {
                this.censusKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CensusTract {
            get {
                return this.censusTractField;
            }
            set {
                this.censusTractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChildrenAgeRange {
            get {
                return this.childrenAgeRangeField;
            }
            set {
                this.childrenAgeRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityAbbreviation {
            get {
                return this.cityAbbreviationField;
            }
            set {
                this.cityAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CongressionalDistrict {
            get {
                return this.congressionalDistrictField;
            }
            set {
                this.congressionalDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountyFIPS {
            get {
                return this.countyFIPSField;
            }
            set {
                this.countyFIPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountySubdivisionCode {
            get {
                return this.countySubdivisionCodeField;
            }
            set {
                this.countySubdivisionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountySubdivisionName {
            get {
                return this.countySubdivisionNameField;
            }
            set {
                this.countySubdivisionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreditCardUser {
            get {
                return this.creditCardUserField;
            }
            set {
                this.creditCardUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DateOfDeath {
            get {
                return this.dateOfDeathField;
            }
            set {
                this.dateOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryIndicator {
            get {
                return this.deliveryIndicatorField;
            }
            set {
                this.deliveryIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryPointCheckDigit {
            get {
                return this.deliveryPointCheckDigitField;
            }
            set {
                this.deliveryPointCheckDigitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryPointCode {
            get {
                return this.deliveryPointCodeField;
            }
            set {
                this.deliveryPointCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DemographicsGender {
            get {
                return this.demographicsGenderField;
            }
            set {
                this.demographicsGenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DemographicsResults {
            get {
                return this.demographicsResultsField;
            }
            set {
                this.demographicsResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistanceAddressToIP {
            get {
                return this.distanceAddressToIPField;
            }
            set {
                this.distanceAddressToIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Education {
            get {
                return this.educationField;
            }
            set {
                this.educationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ElementarySchoolDistrictCode {
            get {
                return this.elementarySchoolDistrictCodeField;
            }
            set {
                this.elementarySchoolDistrictCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ElementarySchoolDistrictName {
            get {
                return this.elementarySchoolDistrictNameField;
            }
            set {
                this.elementarySchoolDistrictNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EstimatedHomeValue {
            get {
                return this.estimatedHomeValueField;
            }
            set {
                this.estimatedHomeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EthnicCode {
            get {
                return this.ethnicCodeField;
            }
            set {
                this.ethnicCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EthnicGroup {
            get {
                return this.ethnicGroupField;
            }
            set {
                this.ethnicGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender2 {
            get {
                return this.gender2Field;
            }
            set {
                this.gender2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HouseholdIncome {
            get {
                return this.householdIncomeField;
            }
            set {
                this.householdIncomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HouseholdSize {
            get {
                return this.householdSizeField;
            }
            set {
                this.householdSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPCity {
            get {
                return this.iPCityField;
            }
            set {
                this.iPCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPConnectionSpeed {
            get {
                return this.iPConnectionSpeedField;
            }
            set {
                this.iPConnectionSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPConnectionType {
            get {
                return this.iPConnectionTypeField;
            }
            set {
                this.iPConnectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPContinent {
            get {
                return this.iPContinentField;
            }
            set {
                this.iPContinentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPCountryAbbreviation {
            get {
                return this.iPCountryAbbreviationField;
            }
            set {
                this.iPCountryAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPCountryName {
            get {
                return this.iPCountryNameField;
            }
            set {
                this.iPCountryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPDomainName {
            get {
                return this.iPDomainNameField;
            }
            set {
                this.iPDomainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPISPName {
            get {
                return this.iPISPNameField;
            }
            set {
                this.iPISPNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPLatitude {
            get {
                return this.iPLatitudeField;
            }
            set {
                this.iPLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPLongitude {
            get {
                return this.iPLongitudeField;
            }
            set {
                this.iPLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPPostalCode {
            get {
                return this.iPPostalCodeField;
            }
            set {
                this.iPPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPProxyDescription {
            get {
                return this.iPProxyDescriptionField;
            }
            set {
                this.iPProxyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPProxyType {
            get {
                return this.iPProxyTypeField;
            }
            set {
                this.iPProxyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPRegion {
            get {
                return this.iPRegionField;
            }
            set {
                this.iPRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPUTC {
            get {
                return this.iPUTCField;
            }
            set {
                this.iPUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LengthOfResidence {
            get {
                return this.lengthOfResidenceField;
            }
            set {
                this.lengthOfResidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MailboxName {
            get {
                return this.mailboxNameField;
            }
            set {
                this.mailboxNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MelissaAddressKey {
            get {
                return this.melissaAddressKeyField;
            }
            set {
                this.melissaAddressKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MelissaAddressKeyBase {
            get {
                return this.melissaAddressKeyBaseField;
            }
            set {
                this.melissaAddressKeyBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MoveDate {
            get {
                return this.moveDateField;
            }
            set {
                this.moveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameFirst {
            get {
                return this.nameFirstField;
            }
            set {
                this.nameFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameFirst2 {
            get {
                return this.nameFirst2Field;
            }
            set {
                this.nameFirst2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameLast {
            get {
                return this.nameLastField;
            }
            set {
                this.nameLastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameLast2 {
            get {
                return this.nameLast2Field;
            }
            set {
                this.nameLast2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameMiddle {
            get {
                return this.nameMiddleField;
            }
            set {
                this.nameMiddleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameMiddle2 {
            get {
                return this.nameMiddle2Field;
            }
            set {
                this.nameMiddle2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NamePrefix {
            get {
                return this.namePrefixField;
            }
            set {
                this.namePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NamePrefix2 {
            get {
                return this.namePrefix2Field;
            }
            set {
                this.namePrefix2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameSuffix {
            get {
                return this.nameSuffixField;
            }
            set {
                this.nameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameSuffix2 {
            get {
                return this.nameSuffix2Field;
            }
            set {
                this.nameSuffix2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NewAreaCode {
            get {
                return this.newAreaCodeField;
            }
            set {
                this.newAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OwnRent {
            get {
                return this.ownRentField;
            }
            set {
                this.ownRentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneCountryCode {
            get {
                return this.phoneCountryCodeField;
            }
            set {
                this.phoneCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneCountryName {
            get {
                return this.phoneCountryNameField;
            }
            set {
                this.phoneCountryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhonePrefix {
            get {
                return this.phonePrefixField;
            }
            set {
                this.phonePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneSuffix {
            get {
                return this.phoneSuffixField;
            }
            set {
                this.phoneSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlaceCode {
            get {
                return this.placeCodeField;
            }
            set {
                this.placeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlaceName {
            get {
                return this.placeNameField;
            }
            set {
                this.placeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Plus4 {
            get {
                return this.plus4Field;
            }
            set {
                this.plus4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PoliticalParty {
            get {
                return this.politicalPartyField;
            }
            set {
                this.politicalPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PresenceOfChildren {
            get {
                return this.presenceOfChildrenField;
            }
            set {
                this.presenceOfChildrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PresenceOfSenior {
            get {
                return this.presenceOfSeniorField;
            }
            set {
                this.presenceOfSeniorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PrivateMailBox {
            get {
                return this.privateMailBoxField;
            }
            set {
                this.privateMailBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecordExtras {
            get {
                return this.recordExtrasField;
            }
            set {
                this.recordExtrasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondarySchoolDistrictCode {
            get {
                return this.secondarySchoolDistrictCodeField;
            }
            set {
                this.secondarySchoolDistrictCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondarySchoolDistrictName {
            get {
                return this.secondarySchoolDistrictNameField;
            }
            set {
                this.secondarySchoolDistrictNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateDistrictLower {
            get {
                return this.stateDistrictLowerField;
            }
            set {
                this.stateDistrictLowerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateDistrictUpper {
            get {
                return this.stateDistrictUpperField;
            }
            set {
                this.stateDistrictUpperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Suite {
            get {
                return this.suiteField;
            }
            set {
                this.suiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TopLevelDomain {
            get {
                return this.topLevelDomainField;
            }
            set {
                this.topLevelDomainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TypesOfVehicles {
            get {
                return this.typesOfVehiclesField;
            }
            set {
                this.typesOfVehiclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UTC {
            get {
                return this.uTCField;
            }
            set {
                this.uTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnifiedSchoolDistrictCode {
            get {
                return this.unifiedSchoolDistrictCodeField;
            }
            set {
                this.unifiedSchoolDistrictCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnifiedSchoolDistrictName {
            get {
                return this.unifiedSchoolDistrictNameField;
            }
            set {
                this.unifiedSchoolDistrictNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UrbanizationName {
            get {
                return this.urbanizationNameField;
            }
            set {
                this.urbanizationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify")]
    public partial class Response {
        
        private ResponseRecord[] recordsField;
        
        private string totalRecordsField;
        
        private string transmissionReferenceField;
        
        private string transmissionResultsField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResponseRecord[] Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransmissionReference {
            get {
                return this.transmissionReferenceField;
            }
            set {
                this.transmissionReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransmissionResults {
            get {
                return this.transmissionResultsField;
            }
            set {
                this.transmissionResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void doContactVerifyCompletedEventHandler(object sender, doContactVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doContactVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doContactVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591